name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".editorconfig"
      - ".gitignore"
      - ".prettierrc.json"
      - ".prettierignore"
      - "cspell.json"
      - "eslint.config.mjs"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # prettier-ignore
    if: '!startsWith(github.event.head_commit.message, ''build(deps-dev): bump the dev-dependencies group'')'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.ACTIONS }}
          manifest-file: ".github/.release-please-manifest.json"
          config-file: ".github/release-please-config.json"
